In [6]:
import random

airlines = ["Delta", "United", "Southwest", "American", "JetBlue"]

random.seed(42)
selected_airline = random.sample(airlines,k=4)
selected_airline

['Delta', 'JetBlue', 'Southwest', 'United']

In [12]:
import pandas as pd

flight_data = pd.read_csv("airlines_flights_data.csv")
flight_data.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [13]:
flight_10 = flight_data.sample(n=10, random_state=42)
flight_10

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
27131,27131,Air_India,AI-506,Delhi,Morning,one,Early_Morning,Kolkata,Economy,19.75,40,7366
266857,266857,Vistara,UK-706,Kolkata,Morning,one,Night,Mumbai,Business,9.83,42,64831
141228,141228,Vistara,UK-772,Kolkata,Morning,one,Night,Bangalore,Economy,10.50,41,6195
288329,288329,Vistara,UK-824,Chennai,Night,one,Morning,Delhi,Business,14.50,14,60160
97334,97334,Air_India,AI-501,Bangalore,Afternoon,one,Night,Mumbai,Economy,8.25,20,6578
135931,135931,AirAsia,I5-510,Kolkata,Early_Morning,one,Afternoon,Bangalore,Economy,10.83,5,4555
290630,290630,Vistara,UK-826,Chennai,Afternoon,zero,Afternoon,Mumbai,Business,2.00,7,23838
141944,141944,Indigo,6.00E-271,Kolkata,Early_Morning,one,Afternoon,Bangalore,Economy,7.75,46,3860
244517,244517,Air_India,AI-619,Mumbai,Night,one,Night,Chennai,Business,26.33,44,32230
215903,215903,Vistara,UK-953,Delhi,Night,one,Evening,Kolkata,Business,20.17,2,76841