In [1]:
import pandas as pd

In [12]:
df_first_name_1 = pd.DataFrame({'Student_ID': ['S1234', 'S4321'], 'First Name': ['Daniel', 'Alfredo']})
df_first_name_2 = pd.DataFrame({'Student_ID': ['S3333', 'S4444'], 'First Name': ['Getrude', 'Ying']})   

df_last_names = pd.DataFrame({'Student_ID': ['S4321', 'S3333', 'S4444', 'S5678'], 'Last Name': ['Smith', 'Gupta', 'Minard', 'Gonzales']})

In [13]:
df_first_name_1

  Student_ID First Name
0      S1234     Daniel
1      S4321    Alfredo

In [14]:
df_first_name_2

  Student_ID First Name
0      S3333    Getrude
1      S4444       Ying

In [15]:
df_last_names

  Student_ID Last Name
0      S4321     Smith
1      S3333     Gupta
2      S4444    Minard
3      S5678  Gonzales

**Union**<br> Specify axis='columns' to concatenate along the columns axis

In [16]:
df_first_names = pd.concat([df_first_name_1, df_first_name_2]).reset_index(drop=True)
df_first_names

  Student_ID First Name
0      S1234     Daniel
1      S4321    Alfredo
2      S3333    Getrude
3      S4444       Ying

**Merge dataframe**

In [17]:
#Inner join

pd.merge(df_first_names, df_last_names, on='Student_ID', how='inner')

  Student_ID First Name Last Name
0      S4321    Alfredo     Smith
1      S3333    Getrude     Gupta
2      S4444       Ying    Minard

In [18]:
pd.merge(df_first_names, df_last_names, on='Student_ID', how='outer')

  Student_ID First Name Last Name
0      S1234     Daniel       NaN
1      S3333    Getrude     Gupta
2      S4321    Alfredo     Smith
3      S4444       Ying    Minard
4      S5678        NaN  Gonzales

In [19]:
pd.merge(df_first_names, df_last_names, on='Student_ID', how='left')

  Student_ID First Name Last Name
0      S1234     Daniel       NaN
1      S4321    Alfredo     Smith
2      S3333    Getrude     Gupta
3      S4444       Ying    Minard

In [20]:
pd.merge(df_first_names, df_last_names, on='Student_ID', how='right')

  Student_ID First Name Last Name
0      S4321    Alfredo     Smith
1      S3333    Getrude     Gupta
2      S4444       Ying    Minard
3      S5678        NaN  Gonzales