In [3]:
import pandas as pd
import numpy as np

from pathlib import Path

original_df = pd.read_csv("employee_attrition.csv")
print(original_df.shape)
original_df.head()

(1470, 26)

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,1,2,Female,94,3,2,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,8,3,Male,61,2,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,2,4,Male,92,2,1,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,3,4,Female,56,3,1,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,2,1,Male,40,3,1,...,3,4,1,6,3,3,2,2,2,2

**Adding new column**

In [5]:
df = original_df.copy()

new_column=range(0,1470)

df['new_column'] = new_column

df

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,new_column
0,41,Yes,Travel_Rarely,1102,1,2,Female,94,3,2,...,1,0,8,0,1,6,4,0,5,0
1,49,No,Travel_Frequently,279,8,3,Male,61,2,2,...,4,1,10,3,3,10,7,1,7,1
2,37,Yes,Travel_Rarely,1373,2,4,Male,92,2,1,...,2,0,7,3,3,0,0,0,0,2
3,33,No,Travel_Frequently,1392,3,4,Female,56,3,1,...,3,0,8,3,3,8,7,3,0,3
4,27,No,Travel_Rarely,591,2,1,Male,40,3,1,...,4,1,6,3,3,2,2,2,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,23,3,Male,41,4,2,...,3,1,17,3,3,5,2,0,3,1465
1466,39,No,Travel_Rarely,613,6,4,Male,42,2,3,...,1,1,9,5,3,7,7,1,7,1466
1467,27,No,Travel_Rarely,155,4,2,Male,87,4,2,...,2,1,6,0,3,6,2,0,3,1467
1468,49,No,Travel_Frequently,1023,2,4,Male,63,2,2,...,4,0,17,3,2,9,6,0,8,1468
1469,34,No,Travel_Rarely,628,8,2,Male,82,4,2,...,1,0,6,3,4,4,3,1,2,1469

In [6]:
df = original_df.copy()

df.Gender = df.Age

df

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,1,2,41,94,3,2,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,8,3,49,61,2,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,2,4,37,92,2,1,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,3,4,33,56,3,1,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,2,1,27,40,3,1,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,23,3,36,41,4,2,...,3,3,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,6,4,39,42,2,3,...,3,1,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,4,2,27,87,4,2,...,4,2,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,2,4,49,63,2,2,...,3,4,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,8,2,34,82,4,2,...,3,1,0,6,3,4,4,3,1,2

In [7]:
df = original_df.copy()

df = df.drop(columns=['Gender','Age'])

df

,Attrition,BusinessTravel,DailyRate,DistanceFromHome,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MaritalStatus,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Yes,Travel_Rarely,1102,1,2,94,3,2,4,Single,...,3,1,0,8,0,1,6,4,0,5
1,No,Travel_Frequently,279,8,3,61,2,2,2,Married,...,4,4,1,10,3,3,10,7,1,7
2,Yes,Travel_Rarely,1373,2,4,92,2,1,3,Single,...,3,2,0,7,3,3,0,0,0,0
3,No,Travel_Frequently,1392,3,4,56,3,1,3,Married,...,3,3,0,8,3,3,8,7,3,0
4,No,Travel_Rarely,591,2,1,40,3,1,2,Married,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,No,Travel_Frequently,884,23,3,41,4,2,4,Married,...,3,3,1,17,3,3,5,2,0,3
1466,No,Travel_Rarely,613,6,4,42,2,3,1,Married,...,3,1,1,9,5,3,7,7,1,7
1467,No,Travel_Rarely,155,4,2,87,4,2,2,Married,...,4,2,1,6,0,3,6,2,0,3
1468,No,Travel_Frequently,1023,2,4,63,2,2,2,Married,...,3,4,0,17,3,2,9,6,0,8
1469,No,Travel_Rarely,628,8,2,82,4,2,3,Married,...,3,1,0,6,3,4,4,3,1,2

In [8]:
df = original_df.copy()

df = df.iloc[:,0:2]

df

      Age Attrition
0      41       Yes
1      49        No
2      37       Yes
3      33        No
4      27        No
...   ...       ...
1465   36        No
1466   39        No
1467   27        No
1468   49        No
1469   34        No

[1470 rows x 2 columns]