##### **OUTLINE**
###### 1.Selecting Data from DataFrame<br>2.Our data<br> 3.Selecting columns with[]<br> 4.Selecting data with loc[]<br> 5.Also iloc[]

In [5]:
import pandas as pd
import numpy as np
from pathlib import Path

df = pd.read_csv('employee_attrition.csv')
print(type(df))
df.head()

<class 'pandas.core.frame.DataFrame'>

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,1,2,Female,94,3,2,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,8,3,Male,61,2,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,2,4,Male,92,2,1,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,3,4,Female,56,3,1,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,2,1,Male,40,3,1,...,3,4,1,6,3,3,2,2,2,2

Selecting Data from DataFrame

In [6]:
age = df['Age']
print(type(age))
age.head()

<class 'pandas.core.series.Series'>

0    41
1    49
2    37
3    33
4    27
Name: Age, dtype: int64

In [7]:
sub_df = df[['Age', 'Attrition', 'DailyRate']]
print(type(sub_df))
sub_df.head()

<class 'pandas.core.frame.DataFrame'>

   Age Attrition  DailyRate
0   41       Yes       1102
1   49        No        279
2   37       Yes       1373
3   33        No       1392
4   27        No        591

In [8]:
year_data = df[[col for col in df.columns if col.startswith('Year')]]
year_data.head()

,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,6,4,0,5
1,10,7,1,7
2,0,0,0,0
3,8,7,3,0
4,2,2,2,2

**Selecting data with loc**

In [9]:
row = df.loc[12:15]

print(type(row))
row

<class 'pandas.core.frame.DataFrame'>

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
12,31,No,Travel_Rarely,670,26,1,Male,31,3,1,...,3,4,1,5,1,2,5,2,4,3
13,34,No,Travel_Rarely,1346,19,2,Male,93,3,1,...,3,3,1,3,2,3,2,2,1,2
14,28,Yes,Travel_Rarely,103,24,3,Male,50,2,1,...,3,2,0,6,4,3,4,2,0,3
15,29,No,Travel_Rarely,1389,21,2,Female,51,4,3,...,3,3,1,10,1,3,10,9,8,8

In [10]:
age_of_emp = df.loc[12:15, 'Age']
print(type(age_of_emp))
age_of_emp

<class 'pandas.core.series.Series'>

12    31
13    34
14    28
15    29
Name: Age, dtype: int64