**Pandas Objects**

The 2 object types used for storing and manipulating data in pandas are
1. Series
2. DataFrame

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

**Series**

A Pandas Series is a one-dimensional array of indexed data

**Creating a series**

Create  a series with list or numpy array

In [4]:
data = pd.Series([0.25 , 0.5 , 0.75 , 1.0])

nparray = np.array([0.25 , 0.5 , 0.75 , 1.0])

data= pd.Series(nparray)
print(type(data))
data

<class 'pandas.core.series.Series'>

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
my_index = list('abcdefg')

data = pd.Series([10, 20, 30, 40, 50, 60, 70], index=my_index)

data

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64

In [6]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64